server.port=${PORT}

spring.datasource.url=jdbc:oracle:thin:@//${ORACLE_IP}:${ORACLE_PORT}/${ORACLE_PDB}
spring.datasource.username=${ORACLE_USERNAME}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=false

cors.allowed-origins=https://cric.react.com, https://cric.vue.com, https://cric.angular.com

spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true
spring.flyway.check-location=true
spring.flyway.enabled=true
spring.flyway.out-of-order=true

# springdoc.api-docs.enabled=false
# springdoc.swagger-ui.configUrl=/swagger.json

logging.level.org.apache.tomcat.util.net.NioEndpoint=OFF

springdoc.api-docs.version=OPENAPI_3_0