CREATE TABLE partnerships (
      id                  NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      innings             NUMBER(1) CHECK (innings BETWEEN 1 AND 4) NOT NULL,
      wicket              NUMBER(2) CHECK (wicket BETWEEN 1 AND 10) NOT NULL,
      runs                NUMBER(4) CHECK (runs BETWEEN 0 AND 2000) NOT NULL,
      balls               NUMBER(4) CHECK (balls BETWEEN 0 AND 2000) NOT NULL,
      ended               BOOLEAN NOT NULL,
      match_player_id_1   NUMBER(10) NOT NULL,
      runs_1              NUMBER(4) CHECK (runs_1 BETWEEN 0 AND 2000) NOT NULL,
      balls_1             NUMBER(4) CHECK (balls_1 BETWEEN 0 AND 2000) NOT NULL,
      match_player_id_2   NUMBER(10) NOT NULL,
      runs_2              NUMBER(4) CHECK (runs_2 BETWEEN 0 AND 2000) NOT NULL,
      balls_2             NUMBER(4) CHECK (balls_2 BETWEEN 0 AND 2000) NOT NULL,
      primary_entry       BOOLEAN NOT NULL,

      CONSTRAINT pk_partnerships PRIMARY KEY (id),

      CONSTRAINT fk_p_match_player_1 FOREIGN KEY (match_player_id_1) REFERENCES match_player_map (id),

      CONSTRAINT fk_p_match_player_2 FOREIGN KEY (match_player_id_2) REFERENCES match_player_map (id),

      CONSTRAINT uk_p_players_innings_wicket UNIQUE (match_player_id_1, match_player_id_2, innings, wicket)
);