CREATE TABLE ballwise_details (
      id                          NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      batsman_match_player_id     NUMBER(10) NOT NULL,
      bowler_match_player_id      NUMBER(10) NOT NULL,
      innings                     NUMBER(1) NOT NULL,
      ball                        NUMBER(4) DEFAULT 0 NOT NULL,
      dismissal                   BOOLEAN NOT NULL,
      total_runs                  NUMBER(1) DEFAULT 0 NOT NULL,
      batsman_runs                NUMBER(1) DEFAULT 0 NOT NULL,
      bowler_runs                 NUMBER(1) DEFAULT 0 NOT NULL,
      extras_runs                 NUMBER(1) DEFAULT 0 NOT NULL,
      extras_type                 VARCHAR2(100),
      timestamp                   NUMBER(15) NOT NULL,

      CONSTRAINT pk_ballwise_details PRIMARY KEY (id),

      CONSTRAINT uk_bd_timestamp UNIQUE (bowler_match_player_id, timestamp),

      CONSTRAINT fk_bd_batsman FOREIGN KEY (batsman_match_player_id) REFERENCES match_player_map (id),

      CONSTRAINT fk_bd_bowler FOREIGN KEY (bowler_match_player_id) REFERENCES match_player_map (id)
);

CREATE INDEX idx_ballwise_details_batsman ON ballwise_details (batsman_match_player_id);

CREATE INDEX idx_ballwise_details_bowler ON ballwise_details (bowler_match_player_id);