UPDATE tags SET type = 'MATCH' WHERE name IN ('FINAL', 'SEMI_FINAL', 'QUARTER_FINAL', 'KNOCKOUT', 'ELIMINATOR', 'THIRD_PLACE', 'QUALIFIER', 'QUALIFIER_1', 'QUALIFIER_2', 'CHALLENGER');

ALTER TABLE tags MODIFY (type VARCHAR2(100) NOT NULL);