CREATE TABLE stadiums
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(200) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100),
    country_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_stadiums PRIMARY KEY (id),
    CONSTRAINT uk_s_name_country_city UNIQUE (name, country_id, city),
    CONSTRAINT fk_stadiums_country_id FOREIGN KEY (country_id) REFERENCES countries (id)
);