CREATE TABLE team_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_team_types PRIMARY KEY (id),
    CONSTRAINT uk_tt_name UNIQUE (name)
);

INSERT INTO team_types (name) VALUES ('International');
INSERT INTO team_types (name) VALUES ('Domestic');
INSERT INTO team_types (name) VALUES ('Franchise');

CREATE TABLE teams
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    country_id NUMBER(19) NOT NULL,
    type_id NUMBER(5) NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (id),
    CONSTRAINT uk_t_name_country_type UNIQUE (name, country_id, type_id),
    CONSTRAINT fk_teams_country_id FOREIGN KEY (country_id) REFERENCES countries (id),
    CONSTRAINT fk_teams_type_id FOREIGN KEY (type_id) REFERENCES team_types (id)
);

