CREATE TABLE tours
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_tours PRIMARY KEY (id),
    CONSTRAINT uk_t_name_start_time UNIQUE (name, start_time)
);