CREATE TABLE players
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    country_id NUMBER(19) NOT NULL,
    date_of_birth DATE NOT NULL,
    image VARCHAR2(255),
    CONSTRAINT pk_players PRIMARY KEY (id),
    CONSTRAINT uk_p_name_country_dob UNIQUE (name, country_id, date_of_birth),
    CONSTRAINT fk_players_country_id FOREIGN KEY (country_id) REFERENCES countries (id)
);