CREATE TABLE series_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_series_types PRIMARY KEY (id),
    CONSTRAINT uk_st_name UNIQUE (name)
);

INSERT INTO series_types (name) VALUES ('Bilateral');
INSERT INTO series_types (name) VALUES ('Tri series');
INSERT INTO series_types (name) VALUES ('Tournament');

CREATE TABLE game_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_game_types PRIMARY KEY (id),
    CONSTRAINT uk_gt_name UNIQUE (name)
);

INSERT INTO game_types (name) VALUES ('ODI');
INSERT INTO game_types (name) VALUES ('Test');
INSERT INTO game_types (name) VALUES ('T20');

CREATE TABLE series
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    home_country_id NUMBER(19) NOT NULL,
    tour_id NUMBER(19) NOT NULL,
    type_id NUMBER(5) NOT NULL,
    game_type_id NUMBER(5) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    CONSTRAINT pk_series PRIMARY KEY (id),
    CONSTRAINT uk_s_name_tour_game_type UNIQUE (name, tour_id, game_type_id),
    CONSTRAINT fk_series_home_country FOREIGN KEY (home_country_id) REFERENCES countries (id),
    CONSTRAINT fk_series_tour FOREIGN KEY (tour_id) REFERENCES tours (id),
    CONSTRAINT fk_series_type FOREIGN KEY (type_id) REFERENCES series_types (id),
    CONSTRAINT fk_series_game_type FOREIGN KEY (game_type_id) REFERENCES game_types (id)
);

CREATE TABLE series_teams_map
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    series_id NUMBER(19) NOT NULL,
    team_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_series_teams_map PRIMARY KEY (id),
    CONSTRAINT uk_stm_series_team UNIQUE (series_id, team_id),
    CONSTRAINT fk_series_teams_map_series FOREIGN KEY (series_id) REFERENCES series (id),
    CONSTRAINT fk_series_teams_map_team FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE TABLE man_of_the_series
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    series_id NUMBER(19) NOT NULL,
    player_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_man_of_the_series PRIMARY KEY (id),
    CONSTRAINT uk_mots_series_player UNIQUE (series_id, player_id),
    CONSTRAINT fk_mots_series FOREIGN KEY (series_id) REFERENCES series (id),
    CONSTRAINT fk_mots_player FOREIGN KEY (player_id) REFERENCES players (id)
);

