CREATE TABLE tags
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_tags PRIMARY KEY (id),
    CONSTRAINT uk_ta_name UNIQUE (name)
);

INSERT INTO tags (name) VALUES ('WORLD_CUP');
INSERT INTO tags (name) VALUES ('IPL');
INSERT INTO tags (name) VALUES ('CHAMPIONS_TROPHY');
INSERT INTO tags (name) VALUES ('BBL');
INSERT INTO tags (name) VALUES ('ILT20');
INSERT INTO tags (name) VALUES ('CHAMPIONS_LEAGUE');
INSERT INTO tags (name) VALUES ('ASIA_CUP');
INSERT INTO tags (name) VALUES ('WTC');

CREATE TABLE tags_map
(
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    entity_type VARCHAR2(100) NOT NULL,
    entity_id NUMBER(10) NOT NULL,
    tag_id NUMBER(5) NOT NULL,
    CONSTRAINT pk_tags_map PRIMARY KEY (id),
    CONSTRAINT uk_tm_type_id_tag UNIQUE (entity_type, entity_id, tag_id),
    CONSTRAINT fk_tm_tag FOREIGN KEY (tag_id) REFERENCES tags (id)
);