CREATE TABLE result_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_result_types PRIMARY KEY (id),
    CONSTRAINT uk_rt_name UNIQUE (name)
);

INSERT INTO result_types (name) VALUES ('Normal');
INSERT INTO result_types (name) VALUES ('Tie');
INSERT INTO result_types (name) VALUES ('Draw');
INSERT INTO result_types (name) VALUES ('Super Over');
INSERT INTO result_types (name) VALUES ('Washed Out');
INSERT INTO result_types (name) VALUES ('Bowl Out');
INSERT INTO result_types (name) VALUES ('Forfeit');
INSERT INTO result_types (name) VALUES ('Least Wickets');
INSERT INTO result_types (name) VALUES ('Boundary Count');


CREATE TABLE win_margin_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_win_margin_types PRIMARY KEY (id),
    CONSTRAINT uk_wmt_name UNIQUE (name)
);

INSERT INTO win_margin_types (name) VALUES ('Run');
INSERT INTO win_margin_types (name) VALUES ('Wicket');


CREATE TABLE matches
(
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    series_id NUMBER(19) NOT NULL,
    team_1_id NUMBER(19) NOT NULL,
    team_2_id NUMBER(19) NOT NULL,
    toss_winner_id NUMBER(19),
    bat_first_id NUMBER(19),
    result_type_id NUMBER(5) NOT NULL,
    winner_id NUMBER(19),
    win_margin NUMBER(5),
    win_margin_type_id NUMBER(5),
    stadium_id NUMBER(19) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    is_official NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_matches PRIMARY KEY (id),
    CONSTRAINT ck_matches_is_official CHECK (is_official IN (0, 1)),
    CONSTRAINT uk_m_stadium_start UNIQUE (stadium_id, start_time),
    CONSTRAINT fk_m_series FOREIGN KEY (series_id) REFERENCES series (id),
    CONSTRAINT fk_m_team_1 FOREIGN KEY (team_1_id) REFERENCES teams (id),
    CONSTRAINT fk_m_team_2 FOREIGN KEY (team_2_id) REFERENCES teams (id),
    CONSTRAINT fk_m_toss_winner FOREIGN KEY (toss_winner_id) REFERENCES teams (id),
    CONSTRAINT fk_m_bat_first FOREIGN KEY (bat_first_id) REFERENCES teams (id),
    CONSTRAINT fk_m_result_type FOREIGN KEY (result_type_id) REFERENCES result_types (id),
    CONSTRAINT fk_m_winner FOREIGN KEY (winner_id) REFERENCES teams (id),
    CONSTRAINT fk_m_win_margin_type FOREIGN KEY (win_margin_type_id) REFERENCES win_margin_types (id),
    CONSTRAINT fk_m_stadium FOREIGN KEY (stadium_id) REFERENCES stadiums (id)
);


CREATE TABLE match_player_map
(
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    match_id NUMBER(10) NOT NULL,
    player_id NUMBER(19) NOT NULL,
    team_id NUMBER(19) NOT NULL,
    CONSTRAINT pk_match_player_map PRIMARY KEY (id),
    CONSTRAINT uk_mpm_match_player_team UNIQUE (match_id, player_id, team_id),
    CONSTRAINT fk_mpm_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_mpm_player FOREIGN KEY (player_id) REFERENCES players (id),
    CONSTRAINT fk_mpm_team FOREIGN KEY (team_id) REFERENCES teams (id)
);


CREATE TABLE dismissal_modes
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(30),
    CONSTRAINT pk_dismissal_modes PRIMARY KEY (id),
    CONSTRAINT uk_dm_name UNIQUE (name)
);

INSERT INTO dismissal_modes (name) VALUES ('Bowled');
INSERT INTO dismissal_modes (name) VALUES ('Caught');
INSERT INTO dismissal_modes (name) VALUES ('LBW');
INSERT INTO dismissal_modes (name) VALUES ('Run Out');
INSERT INTO dismissal_modes (name) VALUES ('Stumped');
INSERT INTO dismissal_modes (name) VALUES ('Hit Twice');
INSERT INTO dismissal_modes (name) VALUES ('Hit Wicket');
INSERT INTO dismissal_modes (name) VALUES ('Obstructing the Field');
INSERT INTO dismissal_modes (name) VALUES ('Timed Out');
INSERT INTO dismissal_modes (name) VALUES ('Retired Hurt');
INSERT INTO dismissal_modes (name) VALUES ('Handled the Ball');


CREATE TABLE batting_scores
(
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    match_player_id NUMBER(10) NOT NULL,
    runs NUMBER(5) DEFAULT 0 NOT NULL,
    balls NUMBER(5) DEFAULT 0 NOT NULL,
    fours NUMBER(5) DEFAULT 0 NOT NULL,
    sixes NUMBER(5) DEFAULT 0 NOT NULL,
    dismissal_mode_id NUMBER(5),
    bowler_id NUMBER(10),
    innings NUMBER(5) NOT NULL,
    position NUMBER(5),
    CONSTRAINT pk_batting_scores PRIMARY KEY (id),
    CONSTRAINT uk_bs_match_player_innings UNIQUE (match_player_id, innings),
    CONSTRAINT fk_bs_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id),
    CONSTRAINT fk_bs_dismissal_mode FOREIGN KEY (dismissal_mode_id) REFERENCES dismissal_modes (id),
    CONSTRAINT fk_bs_bowler FOREIGN KEY (bowler_id) REFERENCES match_player_map (id)
);


CREATE TABLE bowling_figures
(
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    match_player_id NUMBER(10) NOT NULL,
    balls NUMBER(5) DEFAULT 0,
    maidens NUMBER(5) DEFAULT 0,
    runs NUMBER(5) DEFAULT 0,
    wickets NUMBER(5) DEFAULT 0,
    innings NUMBER(5) NOT NULL,
    CONSTRAINT pk_bowling_figures PRIMARY KEY (id),
    CONSTRAINT uk_bf_match_player_innings UNIQUE (match_player_id, innings),
    CONSTRAINT fk_bf_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
);


CREATE TABLE fielder_dismissals
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    score_id NUMBER(10) NOT NULL,
    match_player_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_fielder_dismissals PRIMARY KEY (id),
    CONSTRAINT uk_fd_score_player_team UNIQUE (score_id, match_player_id),
    CONSTRAINT fk_fd_score FOREIGN KEY (score_id) REFERENCES batting_scores (id),
    CONSTRAINT fk_fd_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
);


CREATE TABLE extras_types
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    CONSTRAINT pk_extras_types PRIMARY KEY (id),
    CONSTRAINT uk_et_name UNIQUE (name)
);

INSERT INTO extras_types (name) VALUES ('Bye');
INSERT INTO extras_types (name) VALUES ('Leg Bye');
INSERT INTO extras_types (name) VALUES ('Wide');
INSERT INTO extras_types (name) VALUES ('No Ball');
INSERT INTO extras_types (name) VALUES ('Penalty');


CREATE TABLE extras
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    match_id NUMBER(10) NOT NULL,
    type_id NUMBER(5) NOT NULL,
    runs NUMBER(5) NOT NULL,
    batting_team_id NUMBER(19) NOT NULL,
    bowling_team_id NUMBER(19) NOT NULL,
    innings NUMBER(5) NOT NULL,
    CONSTRAINT pk_extras PRIMARY KEY (id),
    CONSTRAINT uk_e_match_type_batting_innings UNIQUE (match_id, type_id, batting_team_id, innings),
    CONSTRAINT fk_e_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_e_type FOREIGN KEY (type_id) REFERENCES extras_types (id),
    CONSTRAINT fk_e_batting_team FOREIGN KEY (batting_team_id) REFERENCES teams (id),
    CONSTRAINT fk_e_bowling_team FOREIGN KEY (bowling_team_id) REFERENCES teams (id)
);


CREATE TABLE captains
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    match_player_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_captains PRIMARY KEY (id),
    CONSTRAINT uk_c_match_player UNIQUE (match_player_id),
    CONSTRAINT fk_c_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
);


CREATE TABLE wicket_keepers
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    match_player_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_wicket_keepers PRIMARY KEY (id),
    CONSTRAINT uk_wk_match_player UNIQUE (match_player_id),
    CONSTRAINT fk_wk_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
);


CREATE TABLE man_of_the_match
(
    id NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    match_player_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_man_of_the_match PRIMARY KEY (id),
    CONSTRAINT uk_motm_match_player UNIQUE (match_player_id),
    CONSTRAINT fk_motm_match_player FOREIGN KEY (match_player_id) REFERENCES match_player_map (id)
);

CREATE TABLE totals
(
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    match_id NUMBER(10) NOT NULL,
    team_id NUMBER(19) NOT NULL,
    runs NUMBER(5) DEFAULT 0 NOT NULL,
    wickets NUMBER(5) DEFAULT 0,
    balls NUMBER(5) DEFAULT 0 NOT NULL,
    innings NUMBER(5) NOT NULL,
    CONSTRAINT pk_totals PRIMARY KEY (id),
    CONSTRAINT uk_t_match_team_innings UNIQUE (match_id, team_id, innings),
    CONSTRAINT fk_t_match FOREIGN KEY (match_id) REFERENCES matches (id),
    CONSTRAINT fk_t_team FOREIGN KEY (team_id) REFERENCES teams (id)
);

CREATE INDEX idx_totals_team_id ON totals (team_id);
